### ISSUE TITLE
原来你也玩原神~

### ISSUE THREAD

**Issue by cjyx9** [awesomehhhhh/YouxuepaiUtil#9]
啊这,刚回gayhub看看就看到你这头像,b服孤儿来扩个列![](https://i.loli.net/2021/11/25/bBhA4Ss61Ffm2uG.png)

**Comment by awesomehhhhh** [comment]
草，不过我是官服（uid:140309417）![](https://i.loli.net/2021/11/28/ujSWBa3XOPRrJ4A.png)
（另：图床链接不错，我要了.jpg）

**Comment by awesomehhhhh** [comment]
> 啊这,刚回gayhub看看就看到你这头像,b服孤儿来扩个列![](https://camo.githubusercontent.com/5208787ba8b388f032aab770ebfbc119a0b9862bda1e4061f5e8f1252a23f0a9/68747470733a2f2f692e6c6f6c692e6e65742f323032312f31312f32352f62426841345373363146666d3275472e706e67)
